var myString;
var myNum;
var myBool;
var myVar;
// let strArr: string[];
// let numArr: number[];
// let boolArr: boolean[];
var strArr;
var numArr;
var boolArr;
var strNumTuple;
myString = 'Hello'.slice(0, 3);
myNum = 22 + 5.5;
myBool = true;
myVar = false;
numArr = [123, 123, 1];
strArr = ['Hello', 'World'];
boolArr = [true, false, false];
strNumTuple = ['Hello', 5];
var myVoid = null;
var myVoid2 = undefined;
var myNull = undefined;
var myUndefined = null;
console.log(myNum);
console.log(myBool);
console.log(myString);
console.log(myVar);
console.log(strArr);
console.log(numArr);
console.log(boolArr);
console.log(strNumTuple);
console.log(myVoid);
console.log(myVoid2);
